spring:
  application:
    name: Journal App
  data:
    mongodb:
      host: localhost
      port: 27017
      database: journaldb
      auto-index-creation: true
    redis:
      host: localhost
      port: 6379

server:
    port: 8080
    servlet:
      context-path: /journal