spring:
  profiles:
    active: dev
  mail:
    host: smtp.gmail.com
    port: 587
    username: bhartiabhishek310@gmail.com
    password: xxxx xxxx xxxx xxxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org:
      example:
        journalapp: ERROR
    root: off

weather:
  api:
    key: xxxx