spring:
  application:
    name: Journal App
  data:
    mongodb:
      host: localhost
      port: 27017
      database: journaldb
      auto-index-creation: true
    redis:
      host: redis-18845.crce179.ap-south-1-1.ec2.redns.redis-cloud.com
      port: 18845
      username: default
      password: B3E1aVmcihrqCnhHZ3ppLYnYp4MJKgPa

server:
    port: 8080
    servlet:
      context-path: /journal